/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DESSERTSYSIFTABLE_INTERFACE_H
#define DESSERTSYSIFTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "dessertSysifTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _dessertSysifTable_initialize_interface
        (dessertSysifTable_registration * user_ctx, u_long flags);
    void           
        _dessertSysifTable_shutdown_interface
        (dessertSysifTable_registration * user_ctx);

    dessertSysifTable_registration
        *dessertSysifTable_registration_get(void);

    dessertSysifTable_registration
        *dessertSysifTable_registration_set(dessertSysifTable_registration
                                            * newreg);

    netsnmp_container *dessertSysifTable_container_get(void);
    int             dessertSysifTable_container_size(void);

    dessertSysifTable_rowreq_ctx
        *dessertSysifTable_allocate_rowreq_ctx(void *);
    void           
        dessertSysifTable_release_rowreq_ctx(dessertSysifTable_rowreq_ctx *
                                             rowreq_ctx);

    int             dessertSysifTable_index_to_oid(netsnmp_index * oid_idx,
                                                   dessertSysifTable_mib_index
                                                   * mib_idx);
    int             dessertSysifTable_index_from_oid(netsnmp_index *
                                                     oid_idx,
                                                     dessertSysifTable_mib_index
                                                     * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void            dessertSysifTable_valid_columns_set(netsnmp_column_info
                                                        *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTSYSIFTABLE_INTERFACE_H */
/** @} */
