/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file dessertMeshifTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DESSERTMESHIFTABLE_DATA_GET_H
#define DESSERTMESHIFTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dessertMeshifTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * DESSERT-MIB::dessertMeshifTable is subid 5 of dessertObjects.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18898.0.19.10.1.1.5, length: 12
     */
    /*
     * indexes
     */
    int             meshifIndex_map(uint *mib_meshifIndex_val_ptr, uint
                                    raw_meshifIndex_val);

    int             meshifName_map(char **mib_meshifName_val_ptr_ptr,
                                   size_t *mib_meshifName_val_ptr_len_ptr,
                                   char *raw_meshifName_val_ptr,
                                   size_t raw_meshifName_val_ptr_len,
                                   int allow_realloc);
    int             meshifName_get(dessertMeshifTable_rowreq_ctx *
                                   rowreq_ctx,
                                   char **meshifName_val_ptr_ptr,
                                   size_t *meshifName_val_ptr_len_ptr);
    int             meshifMacAddress_map(char
                                         **mib_meshifMacAddress_val_ptr_ptr,
                                         size_t
                                         *mib_meshifMacAddress_val_ptr_len_ptr,
                                         char
                                         *raw_meshifMacAddress_val_ptr,
                                         size_t
                                         raw_meshifMacAddress_val_ptr_len,
                                         int allow_realloc);
    int             meshifMacAddress_get(dessertMeshifTable_rowreq_ctx *
                                         rowreq_ctx,
                                         char
                                         **meshifMacAddress_val_ptr_ptr,
                                         size_t
                                         *meshifMacAddress_val_ptr_len_ptr);
    int             meshifInPkts_map(U64 * mib_meshifInPkts_val_ptr,
                                     U64 raw_meshifInPkts_val);
    int             meshifInPkts_get(dessertMeshifTable_rowreq_ctx *
                                     rowreq_ctx,
                                     U64 * meshifInPkts_val_ptr);
    int             meshifOutPkts_map(U64 * mib_meshifOutPkts_val_ptr,
                                      U64 raw_meshifOutPkts_val);
    int             meshifOutPkts_get(dessertMeshifTable_rowreq_ctx *
                                      rowreq_ctx,
                                      U64 * meshifOutPkts_val_ptr);
    int             meshifInOctets_map(U64 * mib_meshifInOctets_val_ptr,
                                       U64 raw_meshifInOctets_val);
    int             meshifInOctets_get(dessertMeshifTable_rowreq_ctx *
                                       rowreq_ctx,
                                       U64 * meshifInOctets_val_ptr);
    int             meshifOutOctets_map(U64 * mib_meshifOutOctets_val_ptr,
                                        U64 raw_meshifOutOctets_val);
    int             meshifOutOctets_get(dessertMeshifTable_rowreq_ctx *
                                        rowreq_ctx,
                                        U64 * meshifOutOctets_val_ptr);


    int            
        dessertMeshifTable_indexes_set_tbl_idx(dessertMeshifTable_mib_index
                                               * tbl_idx, long meshifIndex_val);
    int            
        dessertMeshifTable_indexes_set(dessertMeshifTable_rowreq_ctx *
                                       rowreq_ctx, long meshifIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTMESHIFTABLE_DATA_GET_H */
/** @} */
