/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef DESSERTSYSIFTABLE_DATA_ACCESS_H
#define DESSERTSYSIFTABLE_DATA_ACCESS_H

#include "dessert_internal.h"

#include "dessertSysifTable.h"

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dessertSysifTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * DESSERT-MIB::dessertSysifTable is subid 7 of dessertObjects.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18898.0.19.10.1.1.7, length: 12
     */


    int
        dessertSysifTable_init_data(dessertSysifTable_registration *
                                    dessertSysifTable_reg);


    /*
     * TODO:180:o: Review dessertSysifTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DESSERTSYSIFTABLE_CACHE_TIMEOUT   DESSERT_AGENTX_SYSIFTABLE_CACHE_TIMEOUT

    void            dessertSysifTable_container_init(netsnmp_container **
                                                     container_ptr_ptr,
                                                     netsnmp_cache *
                                                     cache);
    void            dessertSysifTable_container_shutdown(netsnmp_container
                                                         * container_ptr);

    int             dessertSysifTable_container_load(netsnmp_container *
                                                     container);
    void            dessertSysifTable_container_free(netsnmp_container *
                                                     container);

    int             dessertSysifTable_cache_load(netsnmp_container *
                                                 container);
    void            dessertSysifTable_cache_free(netsnmp_container *
                                                 container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int             dessertSysifTable_row_prep(dessertSysifTable_rowreq_ctx
                                               * rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTSYSIFTABLE_DATA_ACCESS_H */
