/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DESSERTMESHIFTABLE_OIDS_H
#define DESSERTMESHIFTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table dessertMeshifTable 
     */
#define DESSERTMESHIFTABLE_OID              1,3,6,1,4,1,18898,0,19,10,1,1,5

#define COLUMN_MESHIFINDEX         1

#define COLUMN_MESHIFNAME         2

#define COLUMN_MESHIFMACADDRESS         3

#define COLUMN_MESHIFINPKTS         4

#define COLUMN_MESHIFOUTPKTS         5

#define COLUMN_MESHIFINOCTETS         6

#define COLUMN_MESHIFOUTOCTETS         7


#define DESSERTMESHIFTABLE_MIN_COL   COLUMN_MESHIFNAME
#define DESSERTMESHIFTABLE_MAX_COL   COLUMN_MESHIFOUTOCTETS



#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTMESHIFTABLE_OIDS_H */
