/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DESSERTAPPSTATSTABLE_INTERFACE_H
#define DESSERTAPPSTATSTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "dessertAppStatsTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _dessertAppStatsTable_initialize_interface
        (dessertAppStatsTable_registration * user_ctx, u_long flags);
    void           
        _dessertAppStatsTable_shutdown_interface
        (dessertAppStatsTable_registration * user_ctx);

    dessertAppStatsTable_registration
        *dessertAppStatsTable_registration_get(void);

    dessertAppStatsTable_registration
        *dessertAppStatsTable_registration_set
        (dessertAppStatsTable_registration * newreg);

    netsnmp_container *dessertAppStatsTable_container_get(void);
    int             dessertAppStatsTable_container_size(void);

    dessertAppStatsTable_rowreq_ctx
        *dessertAppStatsTable_allocate_rowreq_ctx(void);
    void           
        dessertAppStatsTable_release_rowreq_ctx
        (dessertAppStatsTable_rowreq_ctx * rowreq_ctx);

    int             dessertAppStatsTable_index_to_oid(netsnmp_index *
                                                      oid_idx,
                                                      dessertAppStatsTable_mib_index
                                                      * mib_idx);
    int             dessertAppStatsTable_index_from_oid(netsnmp_index *
                                                        oid_idx,
                                                        dessertAppStatsTable_mib_index
                                                        * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void           
        dessertAppStatsTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPSTATSTABLE_INTERFACE_H */
/** @} */
