/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DESSERTAPPSTATSTABLE_OIDS_H
#define DESSERTAPPSTATSTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table dessertAppStatsTable 
     */
#define DESSERTAPPSTATSTABLE_OID              1,3,6,1,4,1,18898,0,19,10,1,1,8

#define COLUMN_APPSTATSINDEX         1

#define COLUMN_APPSTATSNAME         2
#define COLUMN_APPSTATSNAME_FLAG    (0x1 << 1)

#define COLUMN_APPSTATSDESC         3
#define COLUMN_APPSTATSDESC_FLAG    (0x1 << 2)

#define COLUMN_APPSTATSNODEORLINK         4
#define COLUMN_APPSTATSNODEORLINK_FLAG    (0x1 << 3)

#define COLUMN_APPSTATSVALUETYPE         5
#define COLUMN_APPSTATSVALUETYPE_FLAG    (0x1 << 4)

#define COLUMN_APPSTATSMACADDRESS1         6
#define COLUMN_APPSTATSMACADDRESS1_FLAG    (0x1 << 5)

#define COLUMN_APPSTATSMACADDRESS2         7
#define COLUMN_APPSTATSMACADDRESS2_FLAG    (0x1 << 6)

#define COLUMN_APPSTATSTRUTHVALUE         8
#define COLUMN_APPSTATSTRUTHVALUE_FLAG    (0x1 << 7)

#define COLUMN_APPSTATSINTEGER32         9
#define COLUMN_APPSTATSINTEGER32_FLAG    (0x1 << 8)

#define COLUMN_APPSTATSUNSIGNED32         10
#define COLUMN_APPSTATSUNSIGNED32_FLAG    (0x1 << 9)

#define COLUMN_APPSTATSCOUNTER64         11
#define COLUMN_APPSTATSCOUNTER64_FLAG    (0x1 << 10)

#define COLUMN_APPSTATSOCTETSTRING         12
#define COLUMN_APPSTATSOCTETSTRING_FLAG    (0x1 << 11)


#define DESSERTAPPSTATSTABLE_MIN_COL   COLUMN_APPSTATSNAME
#define DESSERTAPPSTATSTABLE_MAX_COL   COLUMN_APPSTATSOCTETSTRING



#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPSTATSTABLE_OIDS_H */
