/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for dessertMeshifTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dessertMeshifTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "dessertMeshifTable_interface.h"

oid             dessertMeshifTable_oid[] = { DESSERTMESHIFTABLE_OID };

int             dessertMeshifTable_oid_size =
OID_LENGTH(dessertMeshifTable_oid);

dessertMeshifTable_registration dessertMeshifTable_user_context;

void            initialize_table_dessertMeshifTable(void);
void            shutdown_table_dessertMeshifTable(void);


/**
 * Initializes the dessertMeshifTable module
 */
void
init_dessertMeshifTable(void)
{
    DEBUGMSGTL(("verbose:dessertMeshifTable:init_dessertMeshifTable",
                "called\n"));

    /*
     * TODO:300:o: Perform dessertMeshifTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("dessertMeshifTable"))
        initialize_table_dessertMeshifTable();

}                               /* init_dessertMeshifTable */

/**
 * Shut-down the dessertMeshifTable module (agent is exiting)
 */
void
shutdown_dessertMeshifTable(void)
{
    if (should_init("dessertMeshifTable"))
        shutdown_table_dessertMeshifTable();

}

/**
 * Initialize the table dessertMeshifTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_dessertMeshifTable(void)
{
    dessertMeshifTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:dessertMeshifTable:initialize_table_dessertMeshifTable", "called\n"));

    /*
     * TODO:301:o: Perform dessertMeshifTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize dessertMeshifTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context =
        netsnmp_create_data_list("dessertMeshifTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _dessertMeshifTable_initialize_interface(user_context, flags);
}                               /* initialize_table_dessertMeshifTable */

/**
 * Shutdown the table dessertMeshifTable 
 */
void
shutdown_table_dessertMeshifTable(void)
{
    /*
     * call interface shutdown code
     */
    _dessertMeshifTable_shutdown_interface
        (&dessertMeshifTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
dessertMeshifTable_rowreq_ctx_init(dessertMeshifTable_rowreq_ctx *
                                   rowreq_ctx, void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:dessertMeshifTable:dessertMeshifTable_rowreq_ctx_init", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:210:o: |-> Perform extra dessertMeshifTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
}                               /* dessertMeshifTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void
dessertMeshifTable_rowreq_ctx_cleanup(dessertMeshifTable_rowreq_ctx *
                                      rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dessertMeshifTable:dessertMeshifTable_rowreq_ctx_cleanup", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:211:o: |-> Perform extra dessertMeshifTable rowreq cleanup.
     */
}                               /* dessertMeshifTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
dessertMeshifTable_pre_request(dessertMeshifTable_registration *
                               user_context)
{
    DEBUGMSGTL(("verbose:dessertMeshifTable:dessertMeshifTable_pre_request", "called\n"));

    /*
     * TODO:510:o: Perform dessertMeshifTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* dessertMeshifTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
dessertMeshifTable_post_request(dessertMeshifTable_registration *
                                user_context, int rc)
{
    DEBUGMSGTL(("verbose:dessertMeshifTable:dessertMeshifTable_post_request", "called\n"));

    /*
     * TODO:511:o: Perform dessertMeshifTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* dessertMeshifTable_post_request */


/** @{ */
