/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dessertAppParamsTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "dessertAppParamsTable_interface.h"

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table dessertAppParamsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DESSERT-MIB::dessertAppParamsTable is subid 9 of dessertObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.18898.0.19.10.1.1.9, length: 13
 */
typedef struct dessertAppParamsTable_interface_ctx_s {

    netsnmp_container *container;
    netsnmp_cache  *cache;

    dessertAppParamsTable_registration *user_ctx;

    netsnmp_table_registration_info tbl_info;

    netsnmp_baby_steps_access_methods access_multiplexer;

    uint           table_dirty;

} dessertAppParamsTable_interface_ctx;

static dessertAppParamsTable_interface_ctx dessertAppParamsTable_if_ctx;

static void    
_dessertAppParamsTable_container_init(dessertAppParamsTable_interface_ctx *
                                      if_ctx);
static void    
_dessertAppParamsTable_container_shutdown
(dessertAppParamsTable_interface_ctx * if_ctx);


netsnmp_container *
dessertAppParamsTable_container_get(void)
{
    return dessertAppParamsTable_if_ctx.container;
}

dessertAppParamsTable_registration *
dessertAppParamsTable_registration_get(void)
{
    return dessertAppParamsTable_if_ctx.user_ctx;
}

dessertAppParamsTable_registration *
dessertAppParamsTable_registration_set(dessertAppParamsTable_registration *
                                       newreg)
{
    dessertAppParamsTable_registration *old =
        dessertAppParamsTable_if_ctx.user_ctx;
    dessertAppParamsTable_if_ctx.user_ctx = newreg;
    return old;
}

int
dessertAppParamsTable_container_size(void)
{
    return CONTAINER_SIZE(dessertAppParamsTable_if_ctx.container);
}

uint
dessertAppParamsTable_dirty_get(void)
{
    return dessertAppParamsTable_if_ctx.table_dirty;
}

void
dessertAppParamsTable_dirty_set(uint status)
{
    DEBUGMSGTL(("dessertAppParamsTable:dessertAppParamsTable_dirty_set",
                "called. was %d, now %d\n",
                dessertAppParamsTable_if_ctx.table_dirty, status));
    dessertAppParamsTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_pre_request;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_post_request;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_object_lookup;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_get_values;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_check_objects;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_undo_setup;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_set_values;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_undo_values;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_commit;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_undo_commit;
static Netsnmp_Node_Handler _mfd_dessertAppParamsTable_irreversible_commit;

NETSNMP_STATIC_INLINE int
_dessertAppParamsTable_undo_column(dessertAppParamsTable_rowreq_ctx *
                                   rowreq_ctx, netsnmp_variable_list * var,
                                   int column);

dessertAppParamsTable_data *dessertAppParamsTable_allocate_data(void);

/**
 * @internal
 * Initialize the table dessertAppParamsTable 
 *    (Define its contents and how it's structured)
 */
void
_dessertAppParamsTable_initialize_interface
    (dessertAppParamsTable_registration * reg_ptr, u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &dessertAppParamsTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info =
        &dessertAppParamsTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int             mfd_modes = 0;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_initialize_interface", "called\n"));


    /*************************************************
     *
     * save interface context for dessertAppParamsTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info, ASN_INTEGER,
                                               /** index: appParamsIndex */
                                     0);

    /*
     * Define the minimum and maximum accessible columns.  This
     * optimizes retrival. 
     */
    tbl_info->min_column = DESSERTAPPPARAMSTABLE_MIN_COL;
    tbl_info->max_column = DESSERTAPPPARAMSTABLE_MAX_COL;

    /*
     * save users context
     */
    dessertAppParamsTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    dessertAppParamsTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _dessertAppParamsTable_container_init(&dessertAppParamsTable_if_ctx);
    if (NULL == dessertAppParamsTable_if_ctx.container) {
        snmp_log(LOG_ERR,
                 "could not initialize container for dessertAppParamsTable\n");
        return;
    }

    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup =
        _mfd_dessertAppParamsTable_object_lookup;
    access_multiplexer->get_values = _mfd_dessertAppParamsTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request =
        _mfd_dessertAppParamsTable_pre_request;
    access_multiplexer->post_request =
        _mfd_dessertAppParamsTable_post_request;


    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks =
        _mfd_dessertAppParamsTable_check_objects;
    access_multiplexer->undo_setup = _mfd_dessertAppParamsTable_undo_setup;
    access_multiplexer->undo_cleanup =
        _mfd_dessertAppParamsTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_dessertAppParamsTable_set_values;
    access_multiplexer->undo_sets = _mfd_dessertAppParamsTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_dessertAppParamsTable_commit;
    access_multiplexer->undo_commit =
        _mfd_dessertAppParamsTable_undo_commit;
    access_multiplexer->irreversible_commit =
        _mfd_dessertAppParamsTable_irreversible_commit;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("dessertAppParamsTable:init_dessertAppParamsTable",
                "Registering dessertAppParamsTable as a mibs-for-dummies table.\n"));
    handler =
        netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo =
        netsnmp_handler_registration_create("dessertAppParamsTable",
                                            handler,
                                            dessertAppParamsTable_oid,
                                            dessertAppParamsTable_oid_size,
                                            HANDLER_CAN_BABY_STEP |
                                            HANDLER_CAN_RWRITE);
    if (NULL == reginfo) {
        snmp_log(LOG_ERR,
                 "error registering table dessertAppParamsTable\n");
        return;
    }
    reginfo->my_reg_void = &dessertAppParamsTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if (access_multiplexer->object_lookup)
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if (access_multiplexer->set_values)
        mfd_modes |= BABY_STEP_SET_VALUES;
    if (access_multiplexer->irreversible_commit)
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if (access_multiplexer->object_syntax_checks)
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if (access_multiplexer->pre_request)
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if (access_multiplexer->post_request)
        mfd_modes |= BABY_STEP_POST_REQUEST;

    if (access_multiplexer->undo_setup)
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if (access_multiplexer->undo_cleanup)
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if (access_multiplexer->undo_sets)
        mfd_modes |= BABY_STEP_UNDO_SETS;

    if (access_multiplexer->row_creation)
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if (access_multiplexer->consistency_checks)
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if (access_multiplexer->commit)
        mfd_modes |= BABY_STEP_COMMIT;
    if (access_multiplexer->undo_commit)
        mfd_modes |= BABY_STEP_UNDO_COMMIT;

    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            dessertAppParamsTable_if_ctx.
                                            container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject cache helper
     */
    if (NULL != dessertAppParamsTable_if_ctx.cache) {
        handler =
            netsnmp_cache_handler_get(dessertAppParamsTable_if_ctx.cache);
        netsnmp_inject_handler(reginfo, handler);
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

}                               /* _dessertAppParamsTable_initialize_interface */

/**
 * @internal
 * Shutdown the table dessertAppParamsTable
 */
void
_dessertAppParamsTable_shutdown_interface
    (dessertAppParamsTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _dessertAppParamsTable_container_shutdown
        (&dessertAppParamsTable_if_ctx);
}

void
dessertAppParamsTable_valid_columns_set(netsnmp_column_info *vc)
{
    dessertAppParamsTable_if_ctx.tbl_info.valid_columns = vc;
}                               /* dessertAppParamsTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
dessertAppParamsTable_index_to_oid(netsnmp_index * oid_idx,
                                   dessertAppParamsTable_mib_index *
                                   mib_idx)
{
    int             err = SNMP_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * appParamsIndex(1)/DessertAppParamsIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
     */
    netsnmp_variable_list var_appParamsIndex;

    /*
     * set up varbinds
     */
    memset(&var_appParamsIndex, 0x00, sizeof(var_appParamsIndex));
    var_appParamsIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_appParamsIndex.next_variable = NULL;


    DEBUGMSGTL(("verbose:dessertAppParamsTable:dessertAppParamsTable_index_to_oid", "called\n"));

    /*
     * appParamsIndex(1)/DessertAppParamsIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H 
     */
    snmp_set_var_value(&var_appParamsIndex,
                       (u_char *) & mib_idx->appParamsIndex,
                       sizeof(mib_idx->appParamsIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                            NULL, 0, &var_appParamsIndex);
    if (err)
        snmp_log(LOG_ERR, "error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_appParamsIndex);

    return err;
}                               /* dessertAppParamsTable_index_to_oid */

/**
 * extract dessertAppParamsTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
dessertAppParamsTable_index_from_oid(netsnmp_index * oid_idx,
                                     dessertAppParamsTable_mib_index *
                                     mib_idx)
{
    int             err = SNMP_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * appParamsIndex(1)/DessertAppParamsIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
     */
    netsnmp_variable_list var_appParamsIndex;

    /*
     * set up varbinds
     */
    memset(&var_appParamsIndex, 0x00, sizeof(var_appParamsIndex));
    var_appParamsIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_appParamsIndex.next_variable = NULL;


    DEBUGMSGTL(("verbose:dessertAppParamsTable:dessertAppParamsTable_index_from_oid", "called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes(oid_idx->oids, oid_idx->len,
                            &var_appParamsIndex);
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
        mib_idx->appParamsIndex =
            *((long *) var_appParamsIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_appParamsIndex);

    return err;
}                               /* dessertAppParamsTable_index_from_oid */


/*
 * dessertAppParamsTable_allocate_data
 *
 * Purpose: create new dessertAppParamsTable_data.
 */
dessertAppParamsTable_data *
dessertAppParamsTable_allocate_data(void)
{
    dessertAppParamsTable_data *rtn =
        SNMP_MALLOC_TYPEDEF(dessertAppParamsTable_data);

    DEBUGMSGTL(("verbose:dessertAppParamsTable:dessertAppParamsTable_allocate_data", "called\n"));

    if (NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "dessertAppParamsTable_data.\n");
    }

    return rtn;
}                               /* dessertAppParamsTable_allocate_data */

/*
 * dessertAppParamsTable_release_data
 *
 * Purpose: release dessertAppParamsTable data.
 */
void
dessertAppParamsTable_release_data(dessertAppParamsTable_data * data)
{
    DEBUGMSGTL(("verbose:dessertAppParamsTable:dessertAppParamsTable_release_data", "called\n"));

    free(data);
}                               /* dessertAppParamsTable_release_data */

/*
 *********************************************************************
 * @internal
 * allocate resources for a dessertAppParamsTable_rowreq_ctx
 */
dessertAppParamsTable_rowreq_ctx *
dessertAppParamsTable_allocate_rowreq_ctx(void)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        SNMP_MALLOC_TYPEDEF(dessertAppParamsTable_rowreq_ctx);

    DEBUGMSGTL(("internal:dessertAppParamsTable:dessertAppParamsTable_allocate_rowreq_ctx", "called\n"));

    if (NULL == rowreq_ctx) {
        snmp_log(LOG_ERR, "Couldn't allocate memory for a "
                 "dessertAppParamsTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->dessertAppParamsTable_data_list = NULL;


    return rowreq_ctx;
}                               /* dessertAppParamsTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a dessertAppParamsTable_rowreq_ctx
 */
void
dessertAppParamsTable_release_rowreq_ctx(dessertAppParamsTable_rowreq_ctx *
                                         rowreq_ctx)
{
    DEBUGMSGTL(("internal:dessertAppParamsTable:dessertAppParamsTable_release_rowreq_ctx", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);


    if (rowreq_ctx->undo)
        dessertAppParamsTable_release_data(rowreq_ctx->undo);

    /*
     * free index oid pointer
     */
    if (rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
}                               /* dessertAppParamsTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_dessertAppParamsTable_pre_request(netsnmp_mib_handler *handler,
                                       netsnmp_handler_registration
                                       *reginfo,
                                       netsnmp_agent_request_info
                                       *agtreq_info,
                                       netsnmp_request_info *requests)
{
    int             rc;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_pre_request", "called\n"));

    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:dessertAppParamsTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }

    rc = dessertAppParamsTable_pre_request(dessertAppParamsTable_if_ctx.
                                           user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dessertAppParamsTable", "error %d from "
                    "dessertAppParamsTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_dessertAppParamsTable_post_request(netsnmp_mib_handler *handler,
                                        netsnmp_handler_registration
                                        *reginfo,
                                        netsnmp_agent_request_info
                                        *agtreq_info,
                                        netsnmp_request_info *requests)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    int             rc, packet_rc;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_post_request", "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        dessertAppParamsTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:dessertAppParamsTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }

    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && dessertAppParamsTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING,
                 "dessertAppParamsTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = dessertAppParamsTable_post_request(dessertAppParamsTable_if_ctx.
                                            user_ctx, packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dessertAppParamsTable", "error %d from "
                    "dessertAppParamsTable_post_request\n", rc));
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_dessertAppParamsTable_object_lookup(netsnmp_mib_handler *handler,
                                         netsnmp_handler_registration
                                         *reginfo,
                                         netsnmp_agent_request_info
                                         *agtreq_info,
                                         netsnmp_request_info *requests)
{
    int             rc = SNMP_ERR_NOERROR;
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_object_lookup", "called\n"));

    /*
     * get our context from mfd
     * dessertAppParamsTable_interface_ctx *if_ctx =
     *             (dessertAppParamsTable_interface_ctx *)reginfo->my_reg_void;
     */

    if (NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        dessertAppParamsTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
}                               /* _mfd_dessertAppParamsTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dessertAppParamsTable_get_column(dessertAppParamsTable_rowreq_ctx *
                                  rowreq_ctx, netsnmp_variable_list * var,
                                  int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * appParamsName(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H 
         */
    case COLUMN_APPPARAMSNAME:
        if (!(COLUMN_APPPARAMSNAME_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsName) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->type = ASN_OCTET_STR;
        rc = appParamsName_get(rowreq_ctx, (char **) &var->val.string,
                               &var->val_len);
        break;

        /*
         * appParamsDesc(3)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H 
         */
    case COLUMN_APPPARAMSDESC:
        if (!(COLUMN_APPPARAMSDESC_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsDesc) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->type = ASN_OCTET_STR;
        rc = appParamsDesc_get(rowreq_ctx, (char **) &var->val.string,
                               &var->val_len);
        break;

        /*
         * appParamsValueType(4)/DessertAppValueType/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_APPPARAMSVALUETYPE:
        if (!
            (COLUMN_APPPARAMSVALUETYPE_FLAG & rowreq_ctx->
             column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsValueType) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->val_len = sizeof(u_long);
        var->type = ASN_INTEGER;
        rc = appParamsValueType_get(rowreq_ctx,
                                    (u_long *) var->val.string);
        break;

        /*
         * appParamsTruthValue(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_APPPARAMSTRUTHVALUE:
        if (!
            (COLUMN_APPPARAMSTRUTHVALUE_FLAG & rowreq_ctx->
             column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsTruthValue) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->val_len = sizeof(u_long);
        var->type = ASN_INTEGER;
        rc = appParamsTruthValue_get(rowreq_ctx,
                                     (u_long *) var->val.string);
        break;

        /*
         * appParamsInteger32(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSINTEGER32:
        if (!
            (COLUMN_APPPARAMSINTEGER32_FLAG & rowreq_ctx->
             column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsInteger32) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->val_len = sizeof(long);
        var->type = ASN_INTEGER;
        rc = appParamsInteger32_get(rowreq_ctx, (long *) var->val.string);
        break;

        /*
         * appParamsUnsigned32(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSUNSIGNED32:
        if (!
            (COLUMN_APPPARAMSUNSIGNED32_FLAG & rowreq_ctx->
             column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsUnsigned32) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = appParamsUnsigned32_get(rowreq_ctx,
                                     (u_long *) var->val.string);
        break;

        /*
         * appParamsOctetString(9)/DessertApplicationOctetString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_APPPARAMSOCTETSTRING:
        if (!
            (COLUMN_APPPARAMSOCTETSTRING_FLAG & rowreq_ctx->
             column_exists_flags)) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "column %d (appParamsOctetString) doesn't exist\n", column));
            return MFD_SKIP;
        }

        var->type = ASN_OCTET_STR;
        rc = appParamsOctetString_get(rowreq_ctx,
                                      (char **) &var->val.string,
                                      &var->val_len);
        break;

    default:
        if (DESSERTAPPPARAMSTABLE_MIN_COL <= column
            && column <= DESSERTAPPPARAMSTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_column", "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                     "unknown column %d in _dessertAppParamsTable_get_column\n",
                     column);
        }
        break;
    }

    return rc;
}                               /* _dessertAppParamsTable_get_column */

int
_mfd_dessertAppParamsTable_get_values(netsnmp_mib_handler *handler,
                                      netsnmp_handler_registration
                                      *reginfo,
                                      netsnmp_agent_request_info
                                      *agtreq_info,
                                      netsnmp_request_info *requests)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    u_char         *old_string;
    void            (*dataFreeHook) (void *);
    int             rc;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    DEBUGMSGTL(("9:dessertAppParamsTable:_mfd_dessertAppParamsTable_get_values", "exists %p\n",  rowreq_ctx->column_exists_flags));

    for (; requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if (NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len =
                sizeof(requests->requestvb->buf);
        } else if (requests->requestvb->buf ==
                   requests->requestvb->val.string) {
            if (requests->requestvb->val_len !=
                sizeof(requests->requestvb->buf))
                requests->requestvb->val_len =
                    sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _dessertAppParamsTable_get_column(rowreq_ctx,
                                               requests->requestvb,
                                               tri->colnum);
        if (rc) {
            if (MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        } else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR, "NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if (rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if (old_string && (old_string != requests->requestvb->buf) &&
            (requests->requestvb->val.string != old_string)) {
            if (dataFreeHook)
                (*dataFreeHook) (old_string);
            else
                free(old_string);
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_get_values */


/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_dessertAppParamsTable_check_column(dessertAppParamsTable_rowreq_ctx *
                                    rowreq_ctx,
                                    netsnmp_variable_list * var,
                                    int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_check_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {
        /*
         * (INDEX) appParamsIndex(1)/DessertAppParamsIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H 
         */
    case COLUMN_APPPARAMSINDEX:
        rc = SNMP_ERR_NOTWRITABLE;      /* can not change index of active row */
        break;

        /*
         * appParamsName(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H 
         */
    case COLUMN_APPPARAMSNAME:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

        /*
         * appParamsDesc(3)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H 
         */
    case COLUMN_APPPARAMSDESC:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

        /*
         * appParamsValueType(4)/DessertAppValueType/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_APPPARAMSVALUETYPE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

        /*
         * appParamsTruthValue(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_APPPARAMSTRUTHVALUE:
        rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                            sizeof(rowreq_ctx->data.
                                                   appParamsTruthValue));
        /*
         * check that the value is one of defined enums 
         */
        if ((SNMPERR_SUCCESS == rc)
            && (*var->val.integer != TRUTHVALUE_TRUE)
            && (*var->val.integer != TRUTHVALUE_FALSE)
            ) {
            rc = SNMP_ERR_WRONGVALUE;
        }
        if (SNMPERR_SUCCESS != rc) {
            DEBUGMSGTL(("dessertAppParamsTable:_dessertAppParamsTable_check_column:appParamsTruthValue", "varbind validation failed (eg bad type or size)\n"));
        } else {
            rc = appParamsTruthValue_check_value(rowreq_ctx,
                                                 *((u_long *) var->val.
                                                   string));
            if ((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc)
                && (MFD_NOT_VALID_NOW != rc)) {
                snmp_log(LOG_ERR,
                         "bad rc %d from appParamsTruthValue_check_value\n",
                         rc);
                rc = SNMP_ERR_GENERR;
            }
        }
        break;

        /*
         * appParamsInteger32(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSINTEGER32:
        rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                            sizeof(rowreq_ctx->data.
                                                   appParamsInteger32));
        if (SNMPERR_SUCCESS != rc) {
            DEBUGMSGTL(("dessertAppParamsTable:_dessertAppParamsTable_check_column:appParamsInteger32", "varbind validation failed (eg bad type or size)\n"));
        } else {
            rc = appParamsInteger32_check_value(rowreq_ctx,
                                                *((long *) var->val.
                                                  string));
            if ((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc)
                && (MFD_NOT_VALID_NOW != rc)) {
                snmp_log(LOG_ERR,
                         "bad rc %d from appParamsInteger32_check_value\n",
                         rc);
                rc = SNMP_ERR_GENERR;
            }
        }
        break;

        /*
         * appParamsUnsigned32(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSUNSIGNED32:
        rc = netsnmp_check_vb_type_and_size(var, ASN_UNSIGNED,
                                            sizeof(rowreq_ctx->data.
                                                   appParamsUnsigned32));
        if (SNMPERR_SUCCESS != rc) {
            DEBUGMSGTL(("dessertAppParamsTable:_dessertAppParamsTable_check_column:appParamsUnsigned32", "varbind validation failed (eg bad type or size)\n"));
        } else {
            rc = appParamsUnsigned32_check_value(rowreq_ctx,
                                                 *((u_long *) var->val.
                                                   string));
            if ((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc)
                && (MFD_NOT_VALID_NOW != rc)) {
                snmp_log(LOG_ERR,
                         "bad rc %d from appParamsUnsigned32_check_value\n",
                         rc);
                rc = SNMP_ERR_GENERR;
            }
        }
        break;

        /*
         * appParamsOctetString(9)/DessertApplicationOctetString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_APPPARAMSOCTETSTRING:
        rc = netsnmp_check_vb_type_and_max_size(var, ASN_OCTET_STR,
                                                sizeof(rowreq_ctx->data.
                                                       appParamsOctetString));
        /*
         * check defined range(s). 
         */
        if ((SNMPERR_SUCCESS == rc)
            && ((var->val_len < 0) || (var->val_len > 1024))
            ) {
            rc = SNMP_ERR_WRONGLENGTH;
        }
        if (SNMPERR_SUCCESS != rc) {
            DEBUGMSGTL(("dessertAppParamsTable:_dessertAppParamsTable_check_column:appParamsOctetString", "varbind validation failed (eg bad type or size)\n"));
        } else {
            rc = appParamsOctetString_check_value(rowreq_ctx,
                                                  (char *) var->val.string,
                                                  var->val_len);
            if ((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc)
                && (MFD_NOT_VALID_NOW != rc)) {
                snmp_log(LOG_ERR,
                         "bad rc %d from appParamsOctetString_check_value\n",
                         rc);
                rc = SNMP_ERR_GENERR;
            }
        }
        break;

    default:    /** We shouldn't get here */
        rc = SNMP_ERR_GENERR;
        snmp_log(LOG_ERR,
                 "unknown column %d in _dessertAppParamsTable_check_column\n",
                 column);
    }

    return rc;
}                               /* _dessertAppParamsTable_check_column */

int
_mfd_dessertAppParamsTable_check_objects(netsnmp_mib_handler *handler,
                                         netsnmp_handler_registration
                                         *reginfo,
                                         netsnmp_agent_request_info
                                         *agtreq_info,
                                         netsnmp_request_info *requests)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    int             rc;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_check_objects", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    for (; requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _dessertAppParamsTable_check_column(rowreq_ctx,
                                                 requests->requestvb,
                                                 tri->colnum);
        if (rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dessertAppParamsTable_undo_setup_column(dessertAppParamsTable_rowreq_ctx *
                                         rowreq_ctx, int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_undo_setup_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * appParamsTruthValue(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_APPPARAMSTRUTHVALUE:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSTRUTHVALUE_FLAG;
        rc = appParamsTruthValue_undo_setup(rowreq_ctx);
        break;

        /*
         * appParamsInteger32(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSINTEGER32:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSINTEGER32_FLAG;
        rc = appParamsInteger32_undo_setup(rowreq_ctx);
        break;

        /*
         * appParamsUnsigned32(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSUNSIGNED32:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSUNSIGNED32_FLAG;
        rc = appParamsUnsigned32_undo_setup(rowreq_ctx);
        break;

        /*
         * appParamsOctetString(9)/DessertApplicationOctetString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_APPPARAMSOCTETSTRING:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSOCTETSTRING_FLAG;
        rc = appParamsOctetString_undo_setup(rowreq_ctx);
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown column %d in _dessertAppParamsTable_undo_setup_column\n",
                 column);
        break;
    }

    return rc;
}                               /* _dessertAppParamsTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_dessertAppParamsTable_undo_setup(netsnmp_mib_handler *handler,
                                      netsnmp_handler_registration
                                      *reginfo,
                                      netsnmp_agent_request_info
                                      *agtreq_info,
                                      netsnmp_request_info *requests)
{
    int             rc;
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_undo_setup", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = dessertAppParamsTable_allocate_data();
    if (NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests,
                                      SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = dessertAppParamsTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                    "dessertAppParamsTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    } else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info *tri;
        for (; requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if (NULL == tri)
                continue;

            rc = _dessertAppParamsTable_undo_setup_column(rowreq_ctx,
                                                          tri->colnum);
            if (MFD_SUCCESS != rc) {
                DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                            "dessertAppParamsTable_undo_setup_column\n",
                            rc));
                netsnmp_set_request_error(agtreq_info, requests,
                                          SNMP_VALIDATE_ERR(rc));
            }
        }                       /* for results */
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_dessertAppParamsTable_undo_cleanup(netsnmp_mib_handler *handler,
                                        netsnmp_handler_registration
                                        *reginfo,
                                        netsnmp_agent_request_info
                                        *agtreq_info,
                                        netsnmp_request_info *requests)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    int             rc;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_undo_cleanup", "called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = dessertAppParamsTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                    "dessertAppParamsTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if (rowreq_ctx->undo) {
        dessertAppParamsTable_release_data(rowreq_ctx->undo);
        rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dessertAppParamsTable_set_column(dessertAppParamsTable_rowreq_ctx *
                                  rowreq_ctx, netsnmp_variable_list * var,
                                  int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_set_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * appParamsTruthValue(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_APPPARAMSTRUTHVALUE:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSTRUTHVALUE_FLAG;
        rc = appParamsTruthValue_set(rowreq_ctx,
                                     *((u_long *) var->val.string));
        break;

        /*
         * appParamsInteger32(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSINTEGER32:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSINTEGER32_FLAG;
        rc = appParamsInteger32_set(rowreq_ctx,
                                    *((long *) var->val.string));
        break;

        /*
         * appParamsUnsigned32(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSUNSIGNED32:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSUNSIGNED32_FLAG;
        rc = appParamsUnsigned32_set(rowreq_ctx,
                                     *((u_long *) var->val.string));
        break;

        /*
         * appParamsOctetString(9)/DessertApplicationOctetString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_APPPARAMSOCTETSTRING:
        rowreq_ctx->column_set_flags |= COLUMN_APPPARAMSOCTETSTRING_FLAG;
        rc = appParamsOctetString_set(rowreq_ctx, (char *) var->val.string,
                                      var->val_len);
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown column %d in _dessertAppParamsTable_set_column\n",
                 column);
        rc = SNMP_ERR_GENERR;
        break;
    }

    return rc;
}                               /* _dessertAppParamsTable_set_column */

int
_mfd_dessertAppParamsTable_set_values(netsnmp_mib_handler *handler,
                                      netsnmp_handler_registration
                                      *reginfo,
                                      netsnmp_agent_request_info
                                      *agtreq_info,
                                      netsnmp_request_info *requests)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    int             rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_set_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rowreq_ctx->column_set_flags = 0;
    for (; requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _dessertAppParamsTable_set_column(rowreq_ctx,
                                               requests->requestvb,
                                               tri->colnum);
        if (MFD_SUCCESS != rc) {
            DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                        "dessertAppParamsTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests,
                                      SNMP_VALIDATE_ERR(rc));
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_dessertAppParamsTable_commit(netsnmp_mib_handler *handler,
                                  netsnmp_handler_registration *reginfo,
                                  netsnmp_agent_request_info *agtreq_info,
                                  netsnmp_request_info *requests)
{
    int             rc;
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_commit", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rc = dessertAppParamsTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                    "dessertAppParamsTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully committed this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        dessertAppParamsTable_dirty_set(dessertAppParamsTable_dirty_get() + 1); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_dessertAppParamsTable_undo_commit(netsnmp_mib_handler *handler,
                                       netsnmp_handler_registration
                                       *reginfo,
                                       netsnmp_agent_request_info
                                       *agtreq_info,
                                       netsnmp_request_info *requests)
{
    int             rc;
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_undo_commit", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        uint           d = dessertAppParamsTable_dirty_get();

        netsnmp_assert(d != 0);
        if (d)
            dessertAppParamsTable_dirty_set(d - 1);
    }

    rc = dessertAppParamsTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                    "dessertAppParamsTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING,
                 "dessertAppParamsTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dessertAppParamsTable_undo_column(dessertAppParamsTable_rowreq_ctx *
                                   rowreq_ctx, netsnmp_variable_list * var,
                                   int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_undo_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * appParamsTruthValue(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_APPPARAMSTRUTHVALUE:
        rc = appParamsTruthValue_undo(rowreq_ctx);
        break;

        /*
         * appParamsInteger32(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSINTEGER32:
        rc = appParamsInteger32_undo(rowreq_ctx);
        break;

        /*
         * appParamsUnsigned32(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h 
         */
    case COLUMN_APPPARAMSUNSIGNED32:
        rc = appParamsUnsigned32_undo(rowreq_ctx);
        break;

        /*
         * appParamsOctetString(9)/DessertApplicationOctetString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_APPPARAMSOCTETSTRING:
        rc = appParamsOctetString_undo(rowreq_ctx);
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown column %d in _dessertAppParamsTable_undo_column\n",
                 column);
        break;
    }

    return rc;
}                               /* _dessertAppParamsTable_undo_column */

int
_mfd_dessertAppParamsTable_undo_values(netsnmp_mib_handler *handler,
                                       netsnmp_handler_registration
                                       *reginfo,
                                       netsnmp_agent_request_info
                                       *agtreq_info,
                                       netsnmp_request_info *requests)
{
    int             rc;
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_undo_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rc = dessertAppParamsTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                    "dessertAppParamsTable_undo\n", rc));
    }

    for (; requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _dessertAppParamsTable_undo_column(rowreq_ctx,
                                                requests->requestvb,
                                                tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("dessertAppParamsTable:mfd", "error %d from "
                        "dessertAppParamsTable_undo_column\n", rc));
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_dessertAppParamsTable_irreversible_commit(netsnmp_mib_handler
                                               *handler,
                                               netsnmp_handler_registration
                                               *reginfo,
                                               netsnmp_agent_request_info
                                               *agtreq_info,
                                               netsnmp_request_info
                                               *requests)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_dessertAppParamsTable_irreversible:commit", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (!(rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(dessertAppParamsTable_if_ctx.container,
                             rowreq_ctx);
    } else {
        if (rowreq_ctx->column_set_flags) {
            DEBUGMSGTL(("internal:dessertAppParamsTable:_mfd_irreversible_commit", "updating exists (%p) w/set (%p) = %p\n", rowreq_ctx->column_exists_flags, rowreq_ctx->column_set_flags, (rowreq_ctx->column_exists_flags | rowreq_ctx->column_set_flags)));
            rowreq_ctx->column_exists_flags |=
                rowreq_ctx->column_set_flags;
            rowreq_ctx->column_set_flags = 0;
        }
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_dessertAppParamsTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void     _container_free(netsnmp_container * container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache * cache, void *vmagic)
{
    DEBUGMSGTL(("internal:dessertAppParamsTable:_cache_load", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache for dessertAppParamsTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));

    /*
     * call user code
     */
    return dessertAppParamsTable_container_load((netsnmp_container *)
                                                cache->magic);
}                               /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache * cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:dessertAppParamsTable:_cache_free", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache in dessertAppParamsTable_cache_free\n");
        return;
    }

    container = (netsnmp_container *) cache->magic;

    _container_free(container);
}                               /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(dessertAppParamsTable_rowreq_ctx * rowreq_ctx,
                     void *context)
{
    DEBUGMSGTL(("internal:dessertAppParamsTable:_container_item_free",
                "called\n"));

    if (NULL == rowreq_ctx)
        return;

    dessertAppParamsTable_release_rowreq_ctx(rowreq_ctx);
}                               /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("internal:dessertAppParamsTable:_container_free",
                "called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR,
                 "invalid container in dessertAppParamsTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    dessertAppParamsTable_container_free(container);

    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *) _container_item_free,
                    NULL);
}                               /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_dessertAppParamsTable_container_init(dessertAppParamsTable_interface_ctx *
                                      if_ctx)
{
    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_container_init", "called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30,    /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         dessertAppParamsTable_oid,
                                         dessertAppParamsTable_oid_size);

    if (NULL == if_ctx->cache) {
        snmp_log(LOG_ERR,
                 "error creating cache for dessertAppParamsTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    dessertAppParamsTable_container_init(&if_ctx->container,
                                         if_ctx->cache);
    if (NULL == if_ctx->container)
        if_ctx->container =
            netsnmp_container_find
            ("dessertAppParamsTable:table_container");
    if (NULL == if_ctx->container) {
        snmp_log(LOG_ERR, "error creating container in "
                 "dessertAppParamsTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void *) if_ctx->container;
}                               /* _dessertAppParamsTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_dessertAppParamsTable_container_shutdown
    (dessertAppParamsTable_interface_ctx * if_ctx)
{
    DEBUGMSGTL(("internal:dessertAppParamsTable:_dessertAppParamsTable_container_shutdown", "called\n"));

    dessertAppParamsTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

}                               /* _dessertAppParamsTable_container_shutdown */


dessertAppParamsTable_rowreq_ctx *
dessertAppParamsTable_row_find_by_mib_index(dessertAppParamsTable_mib_index
                                            * mib_idx)
{
    dessertAppParamsTable_rowreq_ctx *rowreq_ctx;
    oid             oid_tmp[MAX_OID_LEN];
    netsnmp_index   oid_idx;
    int             rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp) / sizeof(oid);

    /*
     * convert
     */
    rc = dessertAppParamsTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx =
        CONTAINER_FIND(dessertAppParamsTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}
