/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file dessertSysifTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DESSERTSYSIFTABLE_DATA_GET_H
#define DESSERTSYSIFTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dessertSysifTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * DESSERT-MIB::dessertSysifTable is subid 7 of dessertObjects.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18898.0.19.10.1.1.7, length: 12
     */
    /*
     * indexes
     */
    int             sysifIndex_map(uint* *mib_sysifIndex_val_ptr,
                                   uint raw_sysifIndex_val);

    int             sysifName_map(char **mib_sysifName_val_ptr_ptr,
                                  size_t *mib_sysifName_val_ptr_len_ptr,
                                  char *raw_sysifName_val_ptr,
                                  size_t raw_sysifName_val_ptr_len,
                                  int allow_realloc);
    int             sysifName_get(dessertSysifTable_rowreq_ctx *
                                  rowreq_ctx, char **sysifName_val_ptr_ptr,
                                  size_t *sysifName_val_ptr_len_ptr);
    int             sysifMacAddress_map(char
                                        **mib_sysifMacAddress_val_ptr_ptr,
                                        size_t
                                        *mib_sysifMacAddress_val_ptr_len_ptr,
                                        char *raw_sysifMacAddress_val_ptr,
                                        size_t
                                        raw_sysifMacAddress_val_ptr_len,
                                        int allow_realloc);
    int             sysifMacAddress_get(dessertSysifTable_rowreq_ctx *
                                        rowreq_ctx,
                                        char **sysifMacAddress_val_ptr_ptr,
                                        size_t
                                        *sysifMacAddress_val_ptr_len_ptr);
    int             sysifInPkts_map(U64 * mib_sysifInPkts_val_ptr,
                                    U64 raw_sysifInPkts_val);
    int             sysifInPkts_get(dessertSysifTable_rowreq_ctx *
                                    rowreq_ctx, U64 * sysifInPkts_val_ptr);
    int             sysifOutPkts_map(U64 * mib_sysifOutPkts_val_ptr,
                                     U64 raw_sysifOutPkts_val);
    int             sysifOutPkts_get(dessertSysifTable_rowreq_ctx *
                                     rowreq_ctx,
                                     U64 * sysifOutPkts_val_ptr);
    int             sysifInOctets_map(U64 * mib_sysifInOctets_val_ptr,
                                      U64 raw_sysifInOctets_val);
    int             sysifInOctets_get(dessertSysifTable_rowreq_ctx *
                                      rowreq_ctx,
                                      U64 * sysifInOctets_val_ptr);
    int             sysifOutOctets_map(U64 * mib_sysifOutOctets_val_ptr,
                                       U64 raw_sysifOutOctets_val);
    int             sysifOutOctets_get(dessertSysifTable_rowreq_ctx *
                                       rowreq_ctx,
                                       U64 * sysifOutOctets_val_ptr);


    int            
        dessertSysifTable_indexes_set_tbl_idx(dessertSysifTable_mib_index *
                                              tbl_idx, long sysifIndex_val);
    int            
        dessertSysifTable_indexes_set(dessertSysifTable_rowreq_ctx *
                                      rowreq_ctx, long sysifIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTSYSIFTABLE_DATA_GET_H */
/** @} */
