/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DESSERTSYSIFTABLE_OIDS_H
#define DESSERTSYSIFTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table dessertSysifTable 
     */
#define DESSERTSYSIFTABLE_OID              1,3,6,1,4,1,18898,0,19,10,1,1,7

#define COLUMN_SYSIFINDEX         1

#define COLUMN_SYSIFNAME         2

#define COLUMN_SYSIFMACADDRESS         3

#define COLUMN_SYSIFINPKTS         4

#define COLUMN_SYSIFOUTPKTS         5

#define COLUMN_SYSIFINOCTETS         6

#define COLUMN_SYSIFOUTOCTETS         7


#define DESSERTSYSIFTABLE_MIN_COL   COLUMN_SYSIFNAME
#define DESSERTSYSIFTABLE_MAX_COL   COLUMN_SYSIFOUTOCTETS



#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTSYSIFTABLE_OIDS_H */
