/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file dessertAppStatsTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DESSERTAPPSTATSTABLE_DATA_GET_H
#define DESSERTAPPSTATSTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dessertAppStatsTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * DESSERT-MIB::dessertAppStatsTable is subid 8 of dessertObjects.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18898.0.19.10.1.1.8, length: 12
     */
    /*
     * indexes
     */
    int             appStatsIndex_map(uint *mib_appStatsIndex_val_ptr, uint
                                      raw_appStatsIndex_val);

    int             appStatsName_map(char **mib_appStatsName_val_ptr_ptr,
                                     size_t
                                     *mib_appStatsName_val_ptr_len_ptr,
                                     char *raw_appStatsName_val_ptr,
                                     size_t raw_appStatsName_val_ptr_len,
                                     int allow_realloc);
    int             appStatsName_get(dessertAppStatsTable_rowreq_ctx *
                                     rowreq_ctx,
                                     char **appStatsName_val_ptr_ptr,
                                     size_t *appStatsName_val_ptr_len_ptr);
    int             appStatsDesc_map(char **mib_appStatsDesc_val_ptr_ptr,
                                     size_t
                                     *mib_appStatsDesc_val_ptr_len_ptr,
                                     char *raw_appStatsDesc_val_ptr,
                                     size_t raw_appStatsDesc_val_ptr_len,
                                     int allow_realloc);
    int             appStatsDesc_get(dessertAppStatsTable_rowreq_ctx *
                                     rowreq_ctx,
                                     char **appStatsDesc_val_ptr_ptr,
                                     size_t *appStatsDesc_val_ptr_len_ptr);
    int             appStatsNodeOrLink_map(u_long *
                                           mib_appStatsNodeOrLink_val_ptr,
                                           u_long
                                           raw_appStatsNodeOrLink_val);
    int             appStatsNodeOrLink_get(dessertAppStatsTable_rowreq_ctx
                                           * rowreq_ctx,
                                           u_long *
                                           appStatsNodeOrLink_val_ptr);
    int             appStatsValueType_map(u_long *
                                          mib_appStatsValueType_val_ptr,
                                          u_long
                                          raw_appStatsValueType_val);
    int             appStatsValueType_get(dessertAppStatsTable_rowreq_ctx *
                                          rowreq_ctx,
                                          u_long *
                                          appStatsValueType_val_ptr);
    int             appStatsMacAddress1_map(char
                                            **mib_appStatsMacAddress1_val_ptr_ptr,
                                            size_t
                                            *mib_appStatsMacAddress1_val_ptr_len_ptr,
                                            char
                                            *raw_appStatsMacAddress1_val_ptr,
                                            size_t
                                            raw_appStatsMacAddress1_val_ptr_len,
                                            int allow_realloc);
    int             appStatsMacAddress1_get(dessertAppStatsTable_rowreq_ctx
                                            * rowreq_ctx,
                                            char
                                            **appStatsMacAddress1_val_ptr_ptr,
                                            size_t
                                            *appStatsMacAddress1_val_ptr_len_ptr);
    int             appStatsMacAddress2_map(char
                                            **mib_appStatsMacAddress2_val_ptr_ptr,
                                            size_t
                                            *mib_appStatsMacAddress2_val_ptr_len_ptr,
                                            char
                                            *raw_appStatsMacAddress2_val_ptr,
                                            size_t
                                            raw_appStatsMacAddress2_val_ptr_len,
                                            int allow_realloc);
    int             appStatsMacAddress2_get(dessertAppStatsTable_rowreq_ctx
                                            * rowreq_ctx,
                                            char
                                            **appStatsMacAddress2_val_ptr_ptr,
                                            size_t
                                            *appStatsMacAddress2_val_ptr_len_ptr);
    int             appStatsTruthValue_map(u_long *
                                           mib_appStatsTruthValue_val_ptr,
                                           u_long
                                           raw_appStatsTruthValue_val);
    int             appStatsTruthValue_get(dessertAppStatsTable_rowreq_ctx
                                           * rowreq_ctx,
                                           u_long *
                                           appStatsTruthValue_val_ptr);
    int             appStatsInteger32_map(long
                                          *mib_appStatsInteger32_val_ptr,
                                          long raw_appStatsInteger32_val);
    int             appStatsInteger32_get(dessertAppStatsTable_rowreq_ctx *
                                          rowreq_ctx,
                                          long *appStatsInteger32_val_ptr);
    int             appStatsUnsigned32_map(u_long *
                                           mib_appStatsUnsigned32_val_ptr,
                                           u_long
                                           raw_appStatsUnsigned32_val);
    int             appStatsUnsigned32_get(dessertAppStatsTable_rowreq_ctx
                                           * rowreq_ctx,
                                           u_long *
                                           appStatsUnsigned32_val_ptr);
    int             appStatsCounter64_map(U64 *
                                          mib_appStatsCounter64_val_ptr,
                                          U64 raw_appStatsCounter64_val);
    int             appStatsCounter64_get(dessertAppStatsTable_rowreq_ctx *
                                          rowreq_ctx,
                                          U64 * appStatsCounter64_val_ptr);
    int             appStatsOctetString_map(char
                                            **mib_appStatsOctetString_val_ptr_ptr,
                                            size_t
                                            *mib_appStatsOctetString_val_ptr_len_ptr,
                                            char
                                            *raw_appStatsOctetString_val_ptr,
                                            size_t
                                            raw_appStatsOctetString_val_ptr_len,
                                            int allow_realloc);
    int             appStatsOctetString_get(dessertAppStatsTable_rowreq_ctx
                                            * rowreq_ctx,
                                            char
                                            **appStatsOctetString_val_ptr_ptr,
                                            size_t
                                            *appStatsOctetString_val_ptr_len_ptr);


    int            
        dessertAppStatsTable_indexes_set_tbl_idx
        (dessertAppStatsTable_mib_index * tbl_idx, long appStatsIndex_val);
    int            
        dessertAppStatsTable_indexes_set(dessertAppStatsTable_rowreq_ctx *
                                         rowreq_ctx, long appStatsIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPSTATSTABLE_DATA_GET_H */
/** @} */
