/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DESSERTMESHIFTABLE_INTERFACE_H
#define DESSERTMESHIFTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "dessertMeshifTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _dessertMeshifTable_initialize_interface
        (dessertMeshifTable_registration * user_ctx, u_long flags);
    void           
        _dessertMeshifTable_shutdown_interface
        (dessertMeshifTable_registration * user_ctx);

    dessertMeshifTable_registration
        *dessertMeshifTable_registration_get(void);

    dessertMeshifTable_registration
        *dessertMeshifTable_registration_set
        (dessertMeshifTable_registration * newreg);

    netsnmp_container *dessertMeshifTable_container_get(void);
    int             dessertMeshifTable_container_size(void);

    dessertMeshifTable_rowreq_ctx
        *dessertMeshifTable_allocate_rowreq_ctx(void *);
    void           
        dessertMeshifTable_release_rowreq_ctx(dessertMeshifTable_rowreq_ctx
                                              * rowreq_ctx);

    int             dessertMeshifTable_index_to_oid(netsnmp_index *
                                                    oid_idx,
                                                    dessertMeshifTable_mib_index
                                                    * mib_idx);
    int             dessertMeshifTable_index_from_oid(netsnmp_index *
                                                      oid_idx,
                                                      dessertMeshifTable_mib_index
                                                      * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void           
        dessertMeshifTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTMESHIFTABLE_INTERFACE_H */
/** @} */
