/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DESSERTAPPPARAMSTABLE_OIDS_H
#define DESSERTAPPPARAMSTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table dessertAppParamsTable 
     */
#define DESSERTAPPPARAMSTABLE_OID              1,3,6,1,4,1,18898,0,19,10,1,1,9

#define COLUMN_APPPARAMSINDEX         1

#define COLUMN_APPPARAMSNAME         2
#define COLUMN_APPPARAMSNAME_FLAG    (0x1 << 1)

#define COLUMN_APPPARAMSDESC         3
#define COLUMN_APPPARAMSDESC_FLAG    (0x1 << 2)

#define COLUMN_APPPARAMSVALUETYPE         4
#define COLUMN_APPPARAMSVALUETYPE_FLAG    (0x1 << 3)

#define COLUMN_APPPARAMSTRUTHVALUE         5
#define COLUMN_APPPARAMSTRUTHVALUE_FLAG    (0x1 << 4)

#define COLUMN_APPPARAMSINTEGER32         6
#define COLUMN_APPPARAMSINTEGER32_FLAG    (0x1 << 5)

#define COLUMN_APPPARAMSUNSIGNED32         7
#define COLUMN_APPPARAMSUNSIGNED32_FLAG    (0x1 << 6)

#define COLUMN_APPPARAMSOCTETSTRING         9
#define COLUMN_APPPARAMSOCTETSTRING_FLAG    (0x1 << 8)


#define DESSERTAPPPARAMSTABLE_MIN_COL   COLUMN_APPPARAMSNAME
#define DESSERTAPPPARAMSTABLE_MAX_COL   COLUMN_APPPARAMSOCTETSTRING


    /*
     * OR together all the writable cols.
     */
#define DESSERTAPPPARAMSTABLE_SETTABLE_COLS (COLUMN_APPPARAMSTRUTHVALUE_FLAG | COLUMN_APPPARAMSINTEGER32_FLAG | COLUMN_APPPARAMSUNSIGNED32_FLAG | COLUMN_APPPARAMSOCTETSTRING_FLAG)

#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPPARAMSTABLE_OIDS_H */
