/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DESSERTAPPPARAMSTABLE_INTERFACE_H
#define DESSERTAPPPARAMSTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "dessertAppParamsTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _dessertAppParamsTable_initialize_interface
        (dessertAppParamsTable_registration * user_ctx, u_long flags);
    void           
        _dessertAppParamsTable_shutdown_interface
        (dessertAppParamsTable_registration * user_ctx);

    dessertAppParamsTable_registration
        *dessertAppParamsTable_registration_get(void);

    dessertAppParamsTable_registration
        *dessertAppParamsTable_registration_set
        (dessertAppParamsTable_registration * newreg);

    netsnmp_container *dessertAppParamsTable_container_get(void);
    int             dessertAppParamsTable_container_size(void);

    uint           dessertAppParamsTable_dirty_get(void);
    void            dessertAppParamsTable_dirty_set(uint status);

    dessertAppParamsTable_rowreq_ctx
        *dessertAppParamsTable_allocate_rowreq_ctx(void);
    void           
        dessertAppParamsTable_release_rowreq_ctx
        (dessertAppParamsTable_rowreq_ctx * rowreq_ctx);

    int             dessertAppParamsTable_index_to_oid(netsnmp_index *
                                                       oid_idx,
                                                       dessertAppParamsTable_mib_index
                                                       * mib_idx);
    int             dessertAppParamsTable_index_from_oid(netsnmp_index *
                                                         oid_idx,
                                                         dessertAppParamsTable_mib_index
                                                         * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void           
        dessertAppParamsTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPPARAMSTABLE_INTERFACE_H */
/** @} */
