/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-enums.m2c 12526 2005-07-15 22:41:16Z rstory $
 *
 * $Id:$
 */
#ifndef DESSERTAPPSTATSTABLE_ENUMS_H
#define DESSERTAPPSTATSTABLE_ENUMS_H

#include "dessert.h"

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     * NOTES on enums
     * ==============
     *
     * Value Mapping
     * -------------
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them
     * below. For example, a boolean flag (1/0) is usually represented
     * as a TruthValue in a MIB, which maps to the values (1/2).
     *
     */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table dessertAppStatsTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * appStatsNodeOrLink (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef APPSTATSNODEORLINK_ENUMS
#define APPSTATSNODEORLINK_ENUMS

#define APPSTATSNODEORLINK_NONE  0
#define APPSTATSNODEORLINK_NODE  1
#define APPSTATSNODEORLINK_LINK  2

#endif                          /* APPSTATSNODEORLINK_ENUMS */

    /*
     * TODO:140:o: Define your interal representation of appStatsNodeOrLink enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSNODEORLINK_NONE  DESSERT_APPSTATS_NODEORLINK_NONE
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSNODEORLINK_NODE  DESSERT_APPSTATS_NODEORLINK_NODE
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSNODEORLINK_LINK  DESSERT_APPSTATS_NODEORLINK_LINK


/*************************************************************
 * constants for enums for the MIB node
 * appStatsValueType (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef APPSTATSVALUETYPE_ENUMS
#define APPSTATSVALUETYPE_ENUMS

#define APPSTATSVALUETYPE_BOOL  0
#define APPSTATSVALUETYPE_INT32  1
#define APPSTATSVALUETYPE_UINT32  2
#define APPSTATSVALUETYPE_COUNTER64  3
#define APPSTATSVALUETYPE_OCTETSTRING  4

#endif                          /* APPSTATSVALUETYPE_ENUMS */

    /*
     * TODO:140:o: Define your interal representation of appStatsValueType enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSVALUETYPE_BOOL        DESSERT_APPSTATS_VALUETYPE_BOOL
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSVALUETYPE_INT32       DESSERT_APPSTATS_VALUETYPE_INT32
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSVALUETYPE_UINT32      DESSERT_APPSTATS_VALUETYPE_UINT32
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSVALUETYPE_COUNTER64   DESSERT_APPSTATS_VALUETYPE_COUNTER64
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSVALUETYPE_OCTETSTRING DESSERT_APPSTATS_VALUETYPE_OCTETSTRING


/*************************************************************
 * constants for enums for the MIB node
 * appStatsTruthValue (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1
#define TRUTHVALUE_FALSE  2

#endif                          /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define your interal representation of appStatsTruthValue enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSTRUTHVALUE_TRUE  DESSERT_APPSTATS_BOOL_TRUE
#define INTERNAL_DESSERTAPPSTATSTABLE_APPSTATSTRUTHVALUE_FALSE DESSERT_APPSTATS_BOOL_FALSE




#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPSTATSTABLE_ENUMS_H */
