/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for dessertAppStatsTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dessertAppStatsTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "dessertAppStatsTable_interface.h"

oid             dessertAppStatsTable_oid[] = { DESSERTAPPSTATSTABLE_OID };

int             dessertAppStatsTable_oid_size =
OID_LENGTH(dessertAppStatsTable_oid);

dessertAppStatsTable_registration dessertAppStatsTable_user_context;

void            initialize_table_dessertAppStatsTable(void);
void            shutdown_table_dessertAppStatsTable(void);


/**
 * Initializes the dessertAppStatsTable module
 */
void
init_dessertAppStatsTable(void)
{
    DEBUGMSGTL(("verbose:dessertAppStatsTable:init_dessertAppStatsTable",
                "called\n"));

    /*
     * TODO:300:o: Perform dessertAppStatsTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("dessertAppStatsTable"))
        initialize_table_dessertAppStatsTable();

}                               /* init_dessertAppStatsTable */

/**
 * Shut-down the dessertAppStatsTable module (agent is exiting)
 */
void
shutdown_dessertAppStatsTable(void)
{
    if (should_init("dessertAppStatsTable"))
        shutdown_table_dessertAppStatsTable();

}

/**
 * Initialize the table dessertAppStatsTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_dessertAppStatsTable(void)
{
    dessertAppStatsTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:dessertAppStatsTable:initialize_table_dessertAppStatsTable", "called\n"));

    /*
     * TODO:301:o: Perform dessertAppStatsTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize dessertAppStatsTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context =
        netsnmp_create_data_list("dessertAppStatsTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _dessertAppStatsTable_initialize_interface(user_context, flags);
}                               /* initialize_table_dessertAppStatsTable */

/**
 * Shutdown the table dessertAppStatsTable 
 */
void
shutdown_table_dessertAppStatsTable(void)
{
    /*
     * call interface shutdown code
     */
    _dessertAppStatsTable_shutdown_interface
        (&dessertAppStatsTable_user_context);
}

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
dessertAppStatsTable_pre_request(dessertAppStatsTable_registration *
                                 user_context)
{
    DEBUGMSGTL(("verbose:dessertAppStatsTable:dessertAppStatsTable_pre_request", "called\n"));

    /*
     * TODO:510:o: Perform dessertAppStatsTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* dessertAppStatsTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
dessertAppStatsTable_post_request(dessertAppStatsTable_registration *
                                  user_context, int rc)
{
    DEBUGMSGTL(("verbose:dessertAppStatsTable:dessertAppStatsTable_post_request", "called\n"));

    /*
     * TODO:511:o: Perform dessertAppStatsTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* dessertAppStatsTable_post_request */


/** @{ */
