/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef DESSERTAPPSTATSTABLE_DATA_ACCESS_H
#define DESSERTAPPSTATSTABLE_DATA_ACCESS_H

#include "dessert_internal.h"

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dessertAppStatsTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * DESSERT-MIB::dessertAppStatsTable is subid 8 of dessertObjects.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18898.0.19.10.1.1.8, length: 12
     */


    int            
        dessertAppStatsTable_init_data(dessertAppStatsTable_registration *
                                       dessertAppStatsTable_reg);


    /*
     * TODO:180:o: Review dessertAppStatsTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DESSERTAPPSTATSTABLE_CACHE_TIMEOUT   DESSERT_AGENTX_APPSTATSTABLE_CACHE_TIMEOUT

    void            dessertAppStatsTable_container_init(netsnmp_container
                                                        **
                                                        container_ptr_ptr,
                                                        netsnmp_cache *
                                                        cache);
    void           
        dessertAppStatsTable_container_shutdown(netsnmp_container *
                                                container_ptr);

    int             dessertAppStatsTable_container_load(netsnmp_container *
                                                        container);
    void            dessertAppStatsTable_container_free(netsnmp_container *
                                                        container);

    int             dessertAppStatsTable_cache_load(netsnmp_container *
                                                    container);
    void            dessertAppStatsTable_cache_free(netsnmp_container *
                                                    container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int            
        dessertAppStatsTable_row_prep(dessertAppStatsTable_rowreq_ctx *
                                      rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* DESSERTAPPSTATSTABLE_DATA_ACCESS_H */
