/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef DESSERTOBJECTS_H
#define DESSERTOBJECTS_H


/*
 * function declarations 
 */
void            init_dessertObjects(void);
Netsnmp_Node_Handler handle_dessertMeshifNumber;
Netsnmp_Node_Handler handle_applicationVersion;
Netsnmp_Node_Handler handle_protocollShortName;

#endif                          /* DESSERTOBJECTS_H */
